export interface AduModel {
  slug: string;
  name: string;
  size: string;
  sqft: number;
  beds: number;
  baths: number;
  features: string[];
  price: string;
  priceNote: string;
  exteriorImage: string;
  floorPlanImage: string;
}

export const standards = {
  construction: [
    "8' Flat Ceilings",
    '16″ Eaves',
    '100 Amp Service',
    'R-11 Floor Insulation',
    'R-13 Wall Insulation',
    'R-22 Ceiling Insulation',
    'A/C Ready',
  ],
  interior: [
    'Granite Counters',
    'Stainless Steel Under-Mount Kitchen Sink',
    'Kitchen Cabinets with Soft Close Hinges',
    'Deluxe Cabinet Moulding',
    'Appliances: Stove/Oven, Refrigerator, Microwave, Dishwasher',
    '3″ Baseboard Molding',
    '6 Panel Interior Doors',
    'Carpet/Linoleum Flooring',
    'Canned Lights',
  ],
  exterior: [
    'Low-E Dual Glaze Windows',
    'GFCI Receptacles',
    'Frostless Hose Bib',
    'Architectural Shingles',
    '4″ Window Trim',
    'Cement Perforated Soffit',
    'Cement Vertical Siding',
  ],
};

export const upgrades = {
  construction: [
    'All-Electric ADU',
    'Front Porch',
    'Fire Sprinklers',
    'Tankless Water Heater',
  ],
  interior: [
    'Stainless Steel Appliance Package',
    'Fireplace',
    'Arctic White Subway Tile Kitchen Backsplash',
    'Pendant Lights',
    'Farmhouse Top Mount Sink',
    'Crown Molding',
  ],
  exterior: [
    '80″ Windows',
    'Craftsman Window Trim',
    'Full Lap or Board and Batten Siding',
    'French/Sliding Glass Doors',
  ],
};

export const models: AduModel[] = [
  {
    slug: '400a',
    name: 'The 400A',
    size: "15' × 26'",
    sqft: 390,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      "Living room (15' × 15')",
      '1 Bedroom',
      '1 Bathroom',
      'Washer/dryer stack',
      'Water heater included',
    ],
    price: '$195,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/400a/400.webp',
    floorPlanImage: '/images/adu/400a/400-floorplan.png',
  },
  {
    slug: '500',
    name: 'The 500',
    size: "14' × 36'",
    sqft: 500,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      "Living room (19' × 14')",
      '1 Bedroom',
      '1 Bathroom',
      'Stackable washer/dryer',
      'Water heater included',
    ],
    price: '$200,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/500/500.webp',
    floorPlanImage: '/images/adu/500/500-floorplan.webp',
  },
  {
    slug: '600',
    name: 'The 600',
    size: "20' × 30'",
    sqft: 600,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      '1 Bedroom',
      '1 Bathroom',
      'Office',
      'Stackable washer/dryer',
    ],
    price: '$235,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/600/600.png',
    floorPlanImage: '/images/adu/600/600-floorplan.png',
  },
  {
    slug: '700',
    name: 'The 700',
    size: "20' × 37'",
    sqft: 700,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Open plan living',
      'Laundry room',
    ],
    price: '$245,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/700/700.png',
    floorPlanImage: '/images/adu/700/700-floorplan.webp',
  },
  {
    slug: '800a',
    name: 'The 800A',
    size: "20' × 40'",
    sqft: 800,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Open plan living',
      'Laundry room',
    ],
    price: '$250,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/800a/800A.webp',
    floorPlanImage: '/images/adu/800a/800a-floorplan.webp',
  },
  {
    slug: '800b',
    name: 'The 800B',
    size: "23'4\" × 37'",
    sqft: 800,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Open plan living',
      'Laundry room',
    ],
    price: '$265,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/800b/800b.webp',
    floorPlanImage: '/images/adu/800b/800b-floorplan.webp',
  },
  {
    slug: '900',
    name: 'The 900',
    size: "23'4\" × 40'",
    sqft: 900,
    beds: 1,
    baths: 1,
    features: [
      'Full length kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Spacious open plan living',
      'Extra storage',
    ],
    price: '$265,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/900/900.webp',
    floorPlanImage: '/images/adu/900/900-floorplan.webp',
  },
  {
    slug: '1000',
    name: 'The 1000',
    size: "23'4\" × 44'",
    sqft: 1000,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Laundry room',
    ],
    price: '$295,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/1000/1000.png',
    floorPlanImage: '/images/adu/1000/1000-floorplan.webp',
  },
  {
    slug: '1100',
    name: 'The 1100',
    size: "24' × 49'",
    sqft: 1100,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Laundry room',
      'Walk-in closet',
    ],
    price: '$305,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/1100/1100.png',
    floorPlanImage: '/images/adu/1100/1100-floorplan.webp',
  },
  {
    slug: '1200',
    name: 'The 1200',
    size: "23'4\" × 52'",
    sqft: 1200,
    beds: 1,
    baths: 1,
    features: [
      'Full kitchen',
      'Dining area',
      'Living room',
      'Master bedroom',
      'Spacious bathroom',
      'Laundry room',
      'Extra storage',
    ],
    price: '$305,000',
    priceNote: 'Includes foundation, utilities, delivery, and installation',
    exteriorImage: '/images/adu/1200/1200.png',
    floorPlanImage: '/images/adu/1200/1200-floorplan.webp',
  },
];
